### ISSUE TITLE
Unable to Install Package, No "Shipment" Object

### ISSUE THREAD

**Issue by davidlarrimore** [SFDC-Assets/Demo-Cleanup#1]
Installation of the package fails because test classes refer to "Shipment" object which is not part of the package.

![image](https://user-images.githubusercontent.com/5623372/95222841-eca3aa00-07c6-11eb-9222-853ad9212652.png)

**Comment by johnsfdemo** [comment]
Fixed.

**Comment by johnsfdemo** [comment]
Fixed.
